### ISSUE TITLE
How do I stop the nags about the red dots?

### ISSUE THREAD

**Issue by capella07** [Snipaste/feedback#1039]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by liulex** [comment]
Click any of them.

**Comment by navhaxs** [comment]
Hi @liulex 

Firstly I'd like to thank you for Snipaste! Since discovering it last year it has been my favourite snapshot tool without a doubt.

I'd like to suggest that this message about red dots could be clearer. I have been seeing this message for months at every startup because I really did not understand it - I thought the red dots message was talking about the tray icon.

Perhaps the message could be something like "Did you notice the red dots on the snipping toolbar?" 

I know this is a small thing, but I think this will help the average end user in the future :)

**Comment by liulex** [comment]
@navhaxs Thanks for your suggestion! I will improve the message in next update.
