### ISSUE TITLE
Adding 3-option commands to Hotkeys

### ISSUE THREAD

**Issue by tradetheplandan** [Snipaste/feedback#1370]
Hi, I would very much like to request a "tri-option" command string for the hotkeys. Currently, only 2-option commands seem to work (unless I am just not doing it properly). 

Example:
snip -o pin -o clipboard    ... as I would like to snip, then immediately pin it, and then copy it. 
 (1)      (2)            (3)

Most of the time, say for 75% of the images I'm snipping, I do these 3 actions: snip -o pin, and then I copy the image to paste it into Slack (instant messenger). And I probably do this 30x per day. Having the ability to add just one more option at the end of the command (even if the 3rd can ONLY BE copying function [which may be easier for you guys to code?] would make Snipaste 100% completely and utterly perfect :) It's already my favorite snipping app, though, so well-done guys! Sincerely, it really is such a wonderful app. I love it!

For the remaining 25% of images, I do the following steps, in order: snip, pin, draw rectangle, copy, paste into Slack. I can't seem to figure out why when I set the hotkey to snip -o pin the user-defined object I have set to draw isn't automatically selected... I have to first show the toolbar and then select the rectangle. But when I don't first pin it, the rectangle is automatically selected....Maybe later on, even copying automatically after the user-defined object is drawn would be possible. 

Thank you for the best snipping app ever created!
Daniel Roe
danielroe@tradetheplan.com

**Comment by liulex** [comment]
Hi, Daniel,

Multi-output for a single screenshot has just been implemented and will appear in the NEXT release, though PRO version only. You will be able to use `snip -o pin;clipboard;quick-save` to save the screenshot to multiple places. You can even use `snip -o "d:\abc.png";exec:(d:\ocr.exe d:\abc.png)` to send the screenshot to another program.

As for the `snip -o pin` problem, I suppose you are referring the the first feature in [Advanced Tips](https://docs.snipaste.com/advanced-tips). Yes, you cannot automatically select an object after pinned. That's because the rectangles of objects are obtained via their belonging windows, not by image analysis.
