### ISSUE TITLE
Update frequency is so high!!!!! One fix per day.

### ISSUE THREAD

**Issue by THaGKI9** [Snipaste/feedback#490]
I admire your hardwork on the Snipaste about fixing every bugs or adding new features.
But I suffered from everyday notification "new version has release. click to update" and when I check the change log, i found that the update is just something not serious.
So I strongly recommend that you can accumulate some fixes and try to find a proper update frequency. Or just push some new update when there is a serious bug to fix.
Thanks for your good tool.

**Comment by EMLVIRUS** [comment]
I believe high update frequence is only these days.
But I also agree that update period can be a clever idea.

**Comment by taroxd** [comment]
You can disable update checks and check manually whenever you want.

**Comment by THaGKI9** [comment]
ok,a compromise setting.

**Comment by liulex** [comment]
@THaGKI9 
I admit that recent updates (1.13.4, 1.13.5, 1.13.6) were too frequent. I am sorry, but here are the reasons.

I received complaints about frequent updates a long time ago and I was surprised that people didn't like updates. It's just a few clicks to update to a new version since online updater has been implemented.

But I still took the suggestion and reduces the update frequency. Now, for updates meant for new features, the interval is 10 days or more. BUT for updates that fix important bugs, I still think the quicker the better. That's why 1.13.4, 1.13.5 and 1.13.6 were released.

Considering the users may be disappointed that an update arrives without new features, I would also add one or two new features for a bug-fix update. Therefore, 1.13.4 and 1.13.5 are actually bug-fix updates, not new-feature updates. The bugs were actually affecting many users, as you could tell from #457, #479, #480, #481 and #482.

1.13.6 was an update with only one bug fix (for #487). I saw it at 1:00 am and thought it was important, then I fixed and released it about half an hour later. The reason was that 1.13.5 was just released hours ago and only a few people have upgraded to it. If I release the update right away, MOST people can skip 1.13.5 and save one update.

If you are not the victim of a bug, you would think the bug fix is nothing important. This is quite true because the fix make no difference to you. However, for the victims, the bug would prevent them from using the application normally and they really want an instant fix.

Of course, I am the one who introduces the bugs and I apologize for that. I will be more cautious about future updates.

On the user side, apart from disabling the update checks, you can also change the check interval in the preferences. : )

**Comment by liulex** [comment]
One more thing...
Some users also advised me to implement *silent update*. In fact, it is **intended** that the changelog must be shown before you can install the update. Because I really don't like emails and issues that ask about how to use a new feature or why an old functionally is gone.
