### ISSUE TITLE
I would like to know what the Snipaste license model is

### ISSUE THREAD

**Issue by yuryrodrigues** [Snipaste/feedback#507]
Hello,

I would like to know what the Snipaste license model is. Is it free or only free for personal use? GNU, GPL, FOSS?

Grateful!
Yury

**Comment by gloomy-ghost** [comment]
ASAIK it's a close-sourced software. It would be a great news if the author decided to make it FOSS though.

**Comment by yuryrodrigues** [comment]
@gloomy-ghost, Snipaste Is it only free for personal use?

**Comment by EMLVIRUS** [comment]
@yuryrodrigues According to what author says before, there will be a pro version coming soon. You can see #287

**Comment by liulex** [comment]
@yuryrodrigues 
Snipaste will not be open-source in the near future.

Snipaste will always be free for personal use. And for existing versions, it is also free for business use.
However, starting from some future version (possibly Snipaste 2.0+), you would need to acquire a license key in order to use it at work. At that time I will put on a notice on the website.

**Comment by yuryrodrigues** [comment]
@liulex Thanks for the answer. It was not on the site and I was left with this doubt.

**Comment by liulex** [comment]
@yuryrodrigues I have put it on the site. Thanks for reminding.
