### ISSUE TITLE
Feature request: Applying marker pen with blendmode multiply for more legible text

### ISSUE THREAD

**Issue by EsterLoken** [Snipaste/feedback#616]
Applying the marker pen with blendmode multiply would retain the contrast of marked text, making it much more legible, see attached image.

![snipaste_20171103_172557](https://user-images.githubusercontent.com/33354862/32384727-1ee4f1cc-c0bc-11e7-97fb-6e58cb36db55.png)

**Comment by liulex** [comment]
Well, you are the third one that requests this behavior... @wseven7677  and @zhaiyusci also mentioned it in #580 and #596. It's not common for a problem to be mensioned 3 times within 2 months...

My point is that the marker pen in real world does it in the Normal way, not the Multiply way. And the Multiply way may not be good for some pen colors. For example, a white pen would always be invisible. It may confuse the users.

However, thanks to your (@wseven7677, @zhaiyusci  and @EsterLoken ) insist, I finally gave it a try. The result is, for MOST pen colors, the Multiply way does make the text more legible. So ... you will be able to use it in the next release. :)

**Comment by wseven7677** [comment]
@liulex 
Wow it is wonderful that I can use this feature in next release!
What's more, after reading your comment in #580 ,I agreed with your opinion that the multiply way is not perfect for every color.(I didn't reply since i was thinking for resolution..)
However, there is a compromise that you may do special management(use Normal way) for white color(and other similar colors).
Thanks for considering my advice and best wishes for Snipaste~

**Comment by liulex** [comment]
@wseven7677 Thanks for your idea. It does make sense to handle some colors differently.
