### ISSUE TITLE
Washed out colors on MacOS version

### ISSUE THREAD

**Issue by brianleejackson** [Snipaste/feedback#971]
I've been using Snipaste for years now on Windows and recently moved to MacOS. Was happy that there was a beta. However, quickly realized that there is something wrong with how images are saved. 

I put a side by side below... I have tried Monosnap, MacOS snipping tool, etc... they all keep the vibrant screen colors. For some reason Snipaste washes all the colors out, even though I have the quality set to 100. Unfortunately I can't use this for writing my tutorials when color is washed out.

![untitled](https://user-images.githubusercontent.com/186682/44759134-191b7100-aaed-11e8-9f30-7122422f1c6e.png)

Any ideas or settings that can be tweaked?

**Comment by liulex** [comment]
Thanks for reporting. I will look into it.

**Comment by brianleejackson** [comment]
Thanks... just a little more helpful info.

Happens on both my iMac and Macbook Pro. Both are running 10.13.6 macOS High Sierra.

**Comment by RoadToDream** [comment]
@brianleejackson It is duplicated with [#865](https://github.com/Snipaste/feedback/issues/865), and I have made a suggestion for that issue.
The problem happens because the image is assigned withe a wrong color profile. To correct this issue, please use system command _sips_ to correct it. Quick Actions is a good choice to correct the wrongly assigned color profile, mine is attached here. 
[Assign P3.workflow.zip](https://github.com/Snipaste/feedback/files/2591444/Assign.P3.workflow.zip)
For detailed information, please check [Apple Developer Color Management Workflows](https://developer.apple.com/library/archive/technotes/tn2313/_index.html#//apple_ref/doc/uid/DTS40014694-CH1-COLOR_MANAGEMENT_WORKFLOWS)

**Comment by brownsugar** [comment]
Mac 停在 1.16.2 一段時間了，這個版本何時才能取得 😅
